language: java
services:
  - docker

after_success:
  - docker build -t se_methods .
  - docker run se_methods
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
   - docker run --network se-methods se_methods